// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbhkyansuhshrpvifomq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiaGt5YW5zdWhzaHJwdmlmb21xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzQ5OTUsImV4cCI6MjA2NDExMDk5NX0.QR_EvWZX1lcA3gSjPJD4w3ANfVw5v5GWE6uAiEiw6HY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);